default: &default
  adapter: postgresql
  host: localhost
  user: duy
  password: 1

development:
  <<: *default
  database: hotel_dev

test:
  <<: *default
  database: hotel_test

production:
  <<: *default
